apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-config
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  postgresql.conf: |
    # Основные настройки
    listen_addresses = '*'
    port = {{ .Values.postgresql.port | default 5432 }}
    max_connections = {{ .Values.postgresql.config.maxConnections | default 100 }}
    
    # Настройки памяти
    shared_buffers = {{ .Values.postgresql.config.sharedBuffers | default "128MB" }}
    effective_cache_size = {{ .Values.postgresql.config.effectiveCacheSize | default "512MB" }}
    work_mem = {{ .Values.postgresql.config.workMem | default "4MB" }}
    maintenance_work_mem = {{ .Values.postgresql.config.maintenanceWorkMem | default "64MB" }}
    
    # Настройки WAL
    wal_level = {{ .Values.postgresql.replication.enabled | ternary "replica" "minimal" }}
    max_wal_size = {{ .Values.postgresql.config.maxWalSize | default "1GB" }}
    min_wal_size = {{ .Values.postgresql.config.minWalSize | default "80MB" }}
    checkpoint_timeout = {{ .Values.postgresql.config.checkpointTimeout | default "5min" }}
    checkpoint_completion_target = {{ .Values.postgresql.config.checkpointCompletionTarget | default 0.9 }}
    
    # Настройки репликации
    {{- if .Values.postgresql.replication.enabled }}
    hot_standby = on
    max_wal_senders = {{ add .Values.postgresql.replication.slaveReplicas 3 }}
    max_replication_slots = {{ add .Values.postgresql.replication.slaveReplicas 2 }}
    synchronous_commit = {{ .Values.postgresql.replication.synchronousCommit | default "on" }}
    {{- if gt (.Values.postgresql.replication.numSynchronousReplicas | int) 0 }}
    synchronous_standby_names = 'FIRST {{ .Values.postgresql.replication.numSynchronousReplicas }}'
    {{- end }}
    {{- end }}
    
    # Настройки логирования
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/var/log/postgresql'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_rotation_age = 1d
    log_rotation_size = 100MB
    log_truncate_on_rotation = on
    log_min_duration_statement = {{ .Values.postgresql.config.logMinDurationStatement | default -1 }}
    log_checkpoints = {{ .Values.postgresql.config.logCheckpoints | default "off" }}
    log_connections = {{ .Values.postgresql.config.logConnections | default "off" }}
    log_disconnections = {{ .Values.postgresql.config.logDisconnections | default "off" }}
    log_duration = {{ .Values.postgresql.config.logDuration | default "off" }}
    log_line_prefix = '%m [%p] %q%u@%d '
    log_lock_waits = {{ .Values.postgresql.config.logLockWaits | default "off" }}
    log_statement = {{ .Values.postgresql.config.logStatement | default "none" | quote }}
    
    # Настройки статистики
    track_activities = on
    track_counts = on
    track_io_timing = on
    track_functions = {{ .Values.postgresql.config.trackFunctions | default "none" }}
    
    # Настройки автовакуума
    autovacuum = {{ .Values.postgresql.config.autovacuum | default "on" }}
    autovacuum_max_workers = {{ .Values.postgresql.config.autovacuumMaxWorkers | default 3 }}
    autovacuum_naptime = {{ .Values.postgresql.config.autovacuumNaptime | default "1min" }}
    autovacuum_vacuum_threshold = {{ .Values.postgresql.config.autovacuumVacuumThreshold | default 50 }}
    autovacuum_analyze_threshold = {{ .Values.postgresql.config.autovacuumAnalyzeThreshold | default 50 }}
    autovacuum_vacuum_scale_factor = {{ .Values.postgresql.config.autovacuumVacuumScaleFactor | default 0.2 }}
    autovacuum_analyze_scale_factor = {{ .Values.postgresql.config.autovacuumAnalyzeScaleFactor | default 0.1 }}
    
    # Настройки производительности
    random_page_cost = {{ .Values.postgresql.config.randomPageCost | default 4.0 }}
    effective_io_concurrency = {{ .Values.postgresql.config.effectiveIoConcurrency | default 1 }}
    
    # Загружаемые библиотеки
    shared_preload_libraries = '{{ .Values.postgresql.config.sharedPreloadLibraries | default "pg_stat_statements" }}'
    
    {{- if .Values.encryption.ssl.enabled }}
    # Настройки SSL
    ssl = on
    ssl_cert_file = '/etc/postgresql/tls/server.crt'
    ssl_key_file = '/etc/postgresql/tls/server.key'
    {{- if .Values.encryption.ssl.ca }}
    ssl_ca_file = '/etc/postgresql/tls/ca.crt'
    {{- end }}
    {{- if .Values.encryption.ssl.clientAuth }}
    ssl_prefer_server_ciphers = on
    ssl_verify_client = verify-ca
    {{- end }}
    {{- end }}
    
    {{- if .Values.postgresql.config.extraConfig }}
    # Дополнительные настройки
    {{ .Values.postgresql.config.extraConfig }}
    {{- end }}
  
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    
    # "local" is for Unix domain socket connections only
    local   all             all                                     trust
    
    # IPv4 local connections:
    host    all             all             127.0.0.1/32            trust
    
    # IPv6 local connections:
    host    all             all             ::1/128                 trust
    
    # Allow replication connections from localhost, by a user with the replication privilege
    local   replication     all                                     trust
    host    replication     all             127.0.0.1/32            trust
    host    replication     all             ::1/128                 trust
    
    {{- if .Values.postgresql.replication.enabled }}
    # Allow replication connections from all hosts
    host    replication     {{ .Values.postgresql.replication.user }}      all                 md5
    {{- end }}
    
    # Allow connections from all hosts
    host    all             all             all                     md5
    
    {{- if .Values.encryption.ssl.enabled }}
    {{- if .Values.encryption.ssl.clientAuth }}
    # Require SSL connections with client certificate verification
    hostssl all             all             all                     cert
    {{- else }}
    # Allow SSL connections
    hostssl all             all             all                     md5
    {{- end }}
    {{- end }}
    
    {{- if .Values.postgresql.config.extraHbaConfig }}
    # Дополнительные настройки pg_hba.conf
    {{ .Values.postgresql.config.extraHbaConfig }}
    {{- end }} 