apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ include "postgresql.fullname" . }}-0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}-headless
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
    {{- if .Values.metrics.enabled }}
    - port: 9187
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
---
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}-metrics
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  ports:
    - port: 9187
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
{{- end }} 