apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  labels:
    app: postgresql
type: Opaque
stringData:
  postgresql-password: "YourSecurePasswordHere"
  postgresql-replication-password: "YourSecureReplicationPasswordHere" 