{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-credentials
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ include "postgresql.password" . | b64enc | quote }}
  {{- if .Values.postgresql.replication.enabled }}
  postgresql-replication-password: {{ include "postgresql.replicationPassword" . | b64enc | quote }}
  {{- end }}
{{- end }} 